apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-redis
  labels:
    app: internal-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internal-redis
  template:
    metadata:
      labels:
        app: internal-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: internal-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortener-deploy
  labels:
    app: shortener
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: shortener
  template:
    metadata:
      labels:
        app: shortener
    spec:      
      containers:
      - name: shortener-app
        image: asia-east1-docker.pkg.dev/golang-short-url-service/golang-short-url/shortener:v1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: GIN_MODE
          value: "release"
        - name: APP_BASE_URL
          valueFrom: { secretKeyRef: { name: shortener-config, key: app_base_url } }
        - name: POSTGRES_USER
          valueFrom: { secretKeyRef: { name: cloudsql-db-credentials, key: username } }
        - name: POSTGRES_PASSWORD
          valueFrom: { secretKeyRef: { name: cloudsql-db-credentials, key: password } }
        - name: POSTGRES_DB
          valueFrom: { secretKeyRef: { name: cloudsql-db-credentials, key: database } }
        - name: POSTGRES_HOST
          valueFrom: { secretKeyRef: { name: cloudsql-db-credentials, key: db_host } }
        - name: POSTGRES_PORT
          value: "5432"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: AUTH_BASIC_USER
          valueFrom: { secretKeyRef: { name: shortener-auth, key: user } }
        - name: AUTH_BASIC_PASSWORD
          valueFrom: { secretKeyRef: { name: shortener-auth, key: password } }
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","sleep 5"]
        livenessProbe:
          httpGet: { path: /health, port: 8080 }
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet: { path: /health, port: 8080 }
          initialDelaySeconds: 5
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: shortener-service
spec:
  type: ClusterIP
  selector:
    app: shortener
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080